#ifndef LIBOPTIMUSQT_GLOBAL_H
#define LIBOPTIMUSQT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBOPTIMUSQT_LIBRARY)
#  define LIBOPTIMUSQTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBOPTIMUSQTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBOPTIMUSQT_GLOBAL_H
