#ifndef LIBEMPRESASQT_GLOBAL_H
#define LIBEMPRESASQT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBEMPRESASQT_LIBRARY)
#  define LIBEMPRESASQTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBEMPRESASQTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBEMPRESASQT_GLOBAL_H
